#!/usr/bin/env python3
"""
Generate the manuscript's training-configuration table from the config
that the pipeline actually trains with.

Why this exists
---------------
The previous manuscript carried a hand-written hyperparameter table that
was drafted before any experiment ran. When checked against
configs/mrl_inception1d.yaml it disagreed on three settings -- amplitude
scaling, temporal shift, and batch size -- because the table recorded
intentions and the config recorded what happened. A reader reproducing
the work from the paper would have trained a different model.

The fix is structural rather than editorial: the table and the inline
augmentation macros are now emitted from the YAML, so the paper cannot
describe a configuration the code does not run.

Batch size and precision are resolved the same way run_all.sh resolves
them: the environment override (BS, AMP) if set, otherwise the
run_all.sh default. Record the values you actually ran with by setting
those variables when you invoke this script.

    python scripts/emit_config_table.py --paper-dir ../paper
    BS=256 python scripts/emit_config_table.py --paper-dir ../paper
"""

from __future__ import annotations

import argparse
import os
import re

import yaml

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def run_all_default(var: str, fallback: str) -> str:
    """Read `VAR="${VAR:-default}"` from run_all.sh."""
    path = os.path.join(HERE, "run_all.sh")
    if os.path.isfile(path):
        m = re.search(rf'^{var}="\$\{{{var}:-([^}}]*)\}}"',
                      open(path, encoding="utf-8").read(), re.MULTILINE)
        if m:
            return m.group(1)
    return fallback


def fmt_num(x) -> str:
    """1e-3 -> 10^{-3}; plain numbers pass through."""
    if isinstance(x, float) and x != 0 and (abs(x) < 1e-2 or abs(x) >= 1e4):
        exp = int(f"{x:e}".split("e")[1])
        mant = x / 10 ** exp
        return (f"$10^{{{exp}}}$" if abs(mant - 1) < 1e-12
                else f"${mant:g}\\times10^{{{exp}}}$")
    return f"{x:g}" if isinstance(x, float) else str(x)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default="configs/mrl_inception1d.yaml")
    ap.add_argument("--paper-dir", default="../paper")
    args = ap.parse_args()

    cfg = yaml.safe_load(open(os.path.join(HERE, args.config),
                              encoding="utf-8"))
    tr, au, ne = cfg["training"], cfg["augmentation"], cfg["nesting"]

    bs = os.environ.get("BS") or run_all_default("BS", str(tr["batch_size"]))
    amp = os.environ.get("AMP") or run_all_default("AMP", "bf16")
    precision = {"bf16": "bfloat16 autocast", "fp16": "float16 autocast",
                 "off": "float32"}.get(amp, amp)

    sc_lo, sc_hi = au["random_scale"]
    shift = int(au["random_shift"])
    dims = ", ".join(str(d) for d in ne["dims"])

    macros = {
        "CfgBatch": bs,
        "CfgEpochs": tr["epochs"],
        "CfgWarmup": tr["warmup_epochs"],
        "CfgPatience": tr["early_stopping_patience"],
        "CfgNoiseStd": f"{au['gaussian_noise_std']:g}",
        "CfgPNoise": f"{au['p_noise']:g}",
        "CfgScaleLo": f"{sc_lo:g}",
        "CfgScaleHi": f"{sc_hi:g}",
        "CfgPScale": f"{au['p_scale']:g}",
        "CfgShift": shift,
        "CfgPShift": f"{au['p_shift']:g}",
        "CfgPDrop": f"{au['p_lead_dropout']:g}",
        "CfgPrecision": precision,
    }

    gen = os.path.join(args.paper_dir, "generated")
    os.makedirs(gen, exist_ok=True)

    with open(os.path.join(gen, "config.tex"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write("% AUTO-GENERATED by scripts/emit_config_table.py from "
                f"{args.config} -- do not edit.\n")
        for k, v in macros.items():
            f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")

    ls = tr.get("label_smoothing", 0.0)
    table = rf"""% AUTO-GENERATED by scripts/emit_config_table.py from {args.config}
% -- do not edit.  Regenerate after changing the config.
\begin{{table}}[!t]
\centering
\caption{{Training configuration, generated from the released
configuration file so that it cannot describe a model the code does not
train. Identical across all conditions except the factor under
ablation.}}
\label{{tab:config}}
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\begin{{tabular}}{{@{{}}lll@{{}}}}
\toprule
Group & Setting & Value \\
\midrule
\multirow{{5}}{{*}}{{Optimisation}}
 & optimiser      & AdamW~\cite{{loshchilov2019}} \\
 & learning rate $\eta_0$ & {fmt_num(float(tr['learning_rate']))} \\
 & weight decay   & {fmt_num(float(tr['weight_decay']))} (tensors with $\mathrm{{ndim}}>1$) \\
 & batch size     & {bs} \\
 & gradient clip  & {tr['gradient_clip_norm']:g} ($\ell_2$ norm) \\
\midrule
\multirow{{4}}{{*}}{{Schedule}}
 & epochs $t_{{\max}}$ & {tr['epochs']} \\
 & warmup $t_w$      & {tr['warmup_epochs']} epochs, linear \\
 & annealing         & cosine (Eq.~\eqref{{eq:lr}}) \\
 & early stopping    & patience {tr['early_stopping_patience']} on Eq.~\eqref{{eq:selection}} \\
\midrule
\multirow{{3}}{{*}}{{Nesting}}
 & $\mathcal{{M}}$     & $\{{{dims}\}}$ \\
 & weighting         & {ne['weight_strategy'].replace('equal', 'uniform')} (Eq.~\eqref{{eq:weights}}) \\
 & label smoothing   & {ls:g} (ablated at 0.1) \\
\midrule
\multirow{{4}}{{*}}{{Augmentation}}
 & Gaussian noise    & $\sigma_n$={au['gaussian_noise_std']:g}, $p$={au['p_noise']:g} \\
 & amplitude scale   & $\mathcal{{U}}({sc_lo:g},{sc_hi:g})$, $p$={au['p_scale']:g} \\
 & temporal shift    & $\pm${shift} samples, $p$={au['p_shift']:g} \\
 & lead dropout      & 1--2 leads, $p$={au['p_lead_dropout']:g} \\
\midrule
\multirow{{3}}{{*}}{{Protocol}}
 & seeds & \R{{NumSeeds}} (MRL), 2 (XResNet101), 1 (ablations) \\
 & precision & {precision} \\
 & hardware  & single \R{{GPUName}} \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    with open(os.path.join(gen, "tab_config.tex"), "w",
              encoding="utf-8", newline="\n") as f:
        f.write(table)

    print(f"config table written from {args.config}")
    print(f"  batch {bs} | epochs {tr['epochs']} | scale U({sc_lo:g},{sc_hi:g})"
          f" | shift +/-{shift} p={au['p_shift']:g} | {precision}")


if __name__ == "__main__":
    main()
